apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-visit
  labels:
    app: microservice-visit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-visit
  template:
    metadata:
      labels:
        app: microservice-visit
    spec:
      containers:
        - name: microservice-visit
          image: jtan22/microservice-visit:${PROJECT_VERSION}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              value: jdbc:mysql://host.docker.internal/petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-visit
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8083
  selector:
    app: microservice-visit
